---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: romm-smb-assets-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: romm-smb-assets-pv
  storageClassName: smb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
