apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: csi-driver-smb
      version: "v1.19.1"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: kube-system
  values:
    windows:
      enabled: false
