---
apiVersion: v1
kind: Namespace
metadata:
  name: "apps-dev"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps 
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: "apps-dev"
  decryption:
    provider: sops
    secretRef:
      name: sops-age
