apiVersion: v1
stringData:
    VORTEX_BORG_PASSPHRASE: ENC[AES256_GCM,data:5Mk8pzP/oHnW6A==,iv:9mhTJc4A5GYTfc8CJqHWdm7PgrYz0RzSaLPbAozMMmQ=,tag:EHESDKSrUW9y+Mixm+O7Ew==,type:str]
    CLOUDFLARE-DDNS_TOKEN: ENC[AES256_GCM,data:jmoQ9h39YJBydxYVANKtNMKCxqa03HgqNQ1sOmgzl9cz/Rjpukk81w==,iv:hEP3iMMoDGsqINvJlnC6vCGMjm/3Q9MI73MB8z40Pqs=,tag:Q+21T0zQNdIMY/gEg3g7AA==,type:str]
    GLANCE_TOKEN: ENC[AES256_GCM,data:hzoVIkIAC1Ie9zawzCQl10LBumYCMFra23uWihaYqk9fs9CsAAtKVqerdIjJqYBiizjbd7+P1GRseMr556YIynWFPWS1Dar62tw/qrkMPqfkzwGbue6NYQ==,iv:bxlFJkuP57zRug4zH6Vwob4xf+TYXoc0H3sISQXcnvo=,tag:QFQAxFMtnKN7nBhsQGCDuw==,type:str]
    GLANCE_PASSWORD: ENC[AES256_GCM,data:LPL5c+ZT+X+1xgL0Dk4=,iv:2sq6UCzltEO++tAg9WIV8ShY3o46V+7VQzLTKprMUb4=,tag:WMuXypNkEBSXD0GHQF6FTQ==,type:str]
    HOMEDB_POSTGRES_PASSWORD: ENC[AES256_GCM,data:FXsPfKTUYX8=,iv:zvFNz2ru5q+8pM9yE441yB+SggVvnJ3fHC/KoiOhkqU=,tag:D1J76U3mYUx7BcMTP7OMyA==,type:str]
    LINKDING_ADMIN_PASSWORD: ENC[AES256_GCM,data:e1Y48QJEHm6sd6bSEvHzNw==,iv:RSnYwUxb+7XllFHvhaBPvD44VH1iBrhpQhcUAk9tmqg=,tag:b6imw28dxSV4CsdfDwDH+A==,type:str]
    MM_POSTGRES_PASSWORD: ENC[AES256_GCM,data:kk0NcDoqdkD3xyjFt7pf,iv:1hDT+qv1j58yawEpvA7iVSuNTQS5xjv44808ibZsacg=,tag:IZSFJt+1+9PAE12tpE1Cgw==,type:str]
    MM_SQLSETTINGS_DATASOURCE: ENC[AES256_GCM,data:r07QfdqXuJb9H37Bic+aX/cxUxxBpZFHmguombdMFgp18jc+cOk3u/4DDosJwCJiXZ2CYWknLoPYVX0KM4jnl1E1ZI7QuSi14djqKX3qWpZliChnjtI1DbQsG6aXeVlGFPvQ3BI5eaqlyg==,iv:jB0clvNoM/mWRVDlfo5T57LObhoNMFfOk59IqFkuWy4=,tag:B5QX7Nad44T7J+IPmLOG+g==,type:str]
    NEXTCLOUD_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:qi1kpAS7/QmoBE6M9LKdx3jdK4Cg,iv:wXRcblGYL9vVx2Dc+1KSpJewyGJnZy20Eyxa/E78+/k=,tag:/lc0kZSfXZsvSU67YsDhWQ==,type:str]
    NEXTCLOUD_DB_PASSWORD: ENC[AES256_GCM,data:7glID9/noy+SLk2I5MCD7t5bSXzT,iv:0HvpRJFMjhJGrM8RPlU3DEpHi+Ggvv71tekytV+xSns=,tag:FnRglz/mjsjI02Mft8PtdQ==,type:str]
    TWOF_AUTH_APP_KEY: ENC[AES256_GCM,data:qi60qJmgFBVe9nKUf4jNFRW13iO8hrmLdIgYT7TFBmrYYjHRkUTMywHIG0M=,iv:77Tox0bDtKCwlyz9bwVIoUEjmfXqeOoQ0RdU//dsp/M=,tag:5azIPXoxSjkkpWL/6ukoCw==,type:str]
    TWOF_AUTH_MAIL_PASSWORD: ENC[AES256_GCM,data:T7D7AJTpIhs2DNkaDQMQ3Q==,iv:1T49NvOWV3587lChNPXzI1pJqCUm5Qt3YtDTuuZGmA4=,tag:phDKyiBGSaaIev/w/H33nA==,type:str]
    TWOF_AUTH_MAIL_ADDRESS: ENC[AES256_GCM,data:WsSq0ygD9suSlg1NEzmVVscOh6xShtd3Qk4=,iv:dx4aYTH7UaHRwfNNtvDCdiss8osqtdpH7l7FxWtR/TQ=,tag:OzkQ/MRB/TLxjquFxN42Iw==,type:str]
    TORUS_SSH_KEY: ENC[AES256_GCM,data:OwAyxdsK/tKuEP3AMus4h2I4xnVODyjXfPFGfA7n8PTaI441PUVHHsN0T98KqB/1H6hRYw0nVpcGlilb2y88S22KxaRVDgCHvSxzUZVwQZV2spQ47QxdUe/2KRRIqV7rBeIk31DRtzwHGhkeEh9XEUq0ikkOAYNPlwr+CDTo+nvUJiyYasA30a17k6QvqqZHDjQES/5W9GduXA1DEzrMqWlZ+lLME2Jf+tiJCUrDvgQ51p6ljcH7JcpLRGnSUKDr/xjY09ihVEW5Ol56kys5T69JrcwTz8HWonhNjRRMbUbMYEtDOzdIXEvOF/n1FCjEVWvm+Xcm3dD7ZvLfaVjmVMmKDUfUiAM2GWx8Hokn/lZNJv+6JMdl/7hMlQkcRy3YkyTYDsdiwLIJ3ahUArPMUVClS4fWf864q4MWebZCra2S+Wsd11s63WjYB8pKIwnfEFkWM2VEQs1Svrq3OuE1+7ljgc+Dp7m5vHfHUz27gZcX/fpzTHzZqT3rOEBFwus+SFusdOd2zF7LvrA89pii,iv:85SZbc45wx73YWOA/R//yRZGmYrLUk/IHzqPwdcLOWw=,tag:urxgq4whvwd5OpUd3U9wmQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-apps-dev
sops:
    age:
        - recipient: age12pwa382grjgemxk0yzzfmhswnj0fsnmnagtduszhmrgfeqls7grshj3gwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SnBZczdSQWJ6c2VmeVQx
            U0lqTERaYWRkclMrbjR6am82UWtlSW1Fcno4CmZZdzYrLzhBRGo1VE5tVWo0TDhQ
            YThSbWE5WUhEZDEySkt5TUhzUmJaa0UKLS0tIGRGdlNwMG9tbGV1RzkzcU1JK1FE
            UU5LR1c5ZjZ5UWlWWTlzbjBBTVRZSzAK/gVLd4WUxZwH7zQ45C46iLD7uy9P09MZ
            P2qxVteW3lFEjz0L/WggJQlwFSO6W7ekIREqrhtUDJzF5I8zJZzS2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T23:26:01Z"
    mac: ENC[AES256_GCM,data:myWGI1Nzm0xe3KYljBUq86mt16p2wGW+nNNzrB99TMxCvj7Nf81fGC15dyRetFXxQUTAxiqzmu9m6yRRtJ/St/OgBBa7o5rLRYC/WiXxKSwkl4/uOQ0bM6I16KHWGtUFIEx8eDRa3Y/B/oTBsvz99Tb825KWLvPbbaX+Uxvpp+o=,iv:mqKSDvZTDZK9YqR4c63m8AffVQTGwt0aUEdR9IMne6U=,tag:FKDXk1Ed3luQpjhMD1YrWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
