apiVersion: v1
data:
    CLOUDFLARE-DDNS_TOKEN: ENC[AES256_GCM,data:L+20HvjnC9lD7t/upgunlJRdDMv0Ln0ytlhE52bwUes0bvev7Xrcd4GN1imNipEdacuYbkf4Rx4=,iv:Qm2wSLAW3GMHHAJ6R+0k10xxo82AHDA2a6YwggxjnpQ=,tag:0zAFMIZQ57wTEBRc2O3rJQ==,type:str]
    GLANCE_TOKEN: ENC[AES256_GCM,data:QSLU2/0f+Fw/cVTK64rjROi6pUhnz3ESdVjYhh32cIXNgdyhi/v3fbMoMXVOUHHG9nnz+pMQZkpkBwGY2NVQiK7CfemssB11qPNquhHZv1AufvxyK950ER6Rb7k448wsQuubXtDXxKST8LjMHN4c8KJNZC71rtxZ,iv:Zxe6NoP/lNyVpZLfJjK8Imlw2IfgDbAy+0A3c/O8wb4=,tag:1+FKLb3U7MO10oMeMMnBdg==,type:str]
    LINKDING_ADMIN_PASSWORD: ENC[AES256_GCM,data:FUcyR7pmtL79nZQ1U2F5q3uZh2JINjDc,iv:H+k5LH64CmYrtV7jQ+ZkyVgZEU09cT9R8w8LYIP3xuI=,tag:3H6ltdf5jhIO731yXIhbcQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-apps-dev
sops:
    age:
        - recipient: age12pwa382grjgemxk0yzzfmhswnj0fsnmnagtduszhmrgfeqls7grshj3gwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNWRWTkhXaXlVbW1XOFFr
            d0RENFk3Z2hId095aVo0WWI2NmxreXp4UERrCnB2alBwN3hUL3E3TGJwMThiT0pw
            TXNDSXJEV21USEVqaENNOGpEMzU1T3MKLS0tIG8vNmFyZXdaUzk3blM3aDNIdVlS
            QnZ4QXQ1YzhBMUxiZlpsY1llTzltcTgKN+daR9mjA4JB/TplRf/4wDze9JsL/Fkr
            MDHKDTQsJP6hHo84fmnQW7FTKbhS7PIKbDnIHhV5yGQoEis6NPR5NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T07:51:04Z"
    mac: ENC[AES256_GCM,data:VZj+fbJyU1JeYj0zCwDxlsjPfus+iA0mtz8HJFIpztp7tnS9YJy1opRqDaZ4j5H5c3wRMm92DrvxNlFsriUehRxKoA9MItvyhW0xiMpoCl7KOIs+6RkvHkYfIvBIjhgKhVv6YUoPMTT672Kti2eczdXxng5b2hlhuQNOzxyOr7I=,iv:BsUnDuahqsPEfmF3Gvq679wsEu3ow9NsbTKeOogRMdM=,tag:Aj6e93NO259XG25h1zUu0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
